'use client';
import Link from 'next/link';
import { useMaydan } from './context';
import { Icon } from './icon';
import { Action, Badge, Crest, PageTitle, SectionTitle } from './ui';
import { matches, players, teams, teamById, dateLabel, type Match } from '@/lib/maydan/data';

export function Standings({ compact = false }: { compact?: boolean }) {
  const { t } = useMaydan();
  return <div className="md-table-scroll"><table className="md-table standings"><thead><tr><th>#</th><th>{t('Club', 'الفريق')}</th><th>{t('P', 'ل')}</th>{!compact && <><th>{t('W','ف')}</th><th>{t('D','ت')}</th><th>{t('L','خ')}</th><th>{t('GF','له')}</th><th>{t('GA','عليه')}</th></>}<th>{t('GD', 'فارق')}</th><th>{t('Pts', 'نقاط')}</th>{!compact && <th>{t('Last 5', 'آخر ٥')}</th>}</tr></thead><tbody>{teams.slice(0, compact ? 4 : undefined).map((team, i) => <tr key={team.id} className={team.id === 'jenin' ? 'your-team' : ''}><td><span className={`md-rank ${i === 0 ? 'first' : ''}`}>{i + 1}</span></td><td><Link href={`/hub/teams/${team.id}`} className="md-table-team"><Crest team={team} size="sm"/>{t(team.name, team.ar)}{team.id === 'jenin' && <small>{t('YOU', 'أنت')}</small>}</Link></td><td>{team.played}</td>{!compact && <><td>{team.won}</td><td>{team.drawn}</td><td>{team.lost}</td><td>{team.gf}</td><td>{team.ga}</td></>}<td>{team.gf - team.ga > 0 ? '+' : ''}{team.gf - team.ga}</td><td><b>{team.won * 3 + team.drawn}</b></td>{!compact && <td><div className="md-form-dots">{team.form.map((f, j) => <span key={j} className={f.toLowerCase()} title={f === 'W' ? 'Win' : f === 'D' ? 'Draw' : 'Loss'}>{f}</span>)}</div></td>}</tr>)}</tbody></table></div>;
}
export function MatchRow({ match }: { match: Match }) {
  const { t, locale } = useMaydan(); const home = teamById(match.home); const away = teamById(match.away);
  return <Link href={`/hub/matches/${match.id}`} className="md-match-row"><span className="md-match-date"><b>{dateLabel(match.date, locale, { day: '2-digit' })}</b><small>{dateLabel(match.date, locale, { month: 'short' })}</small></span><span className="md-match-team home"><span>{t(home.name, home.ar)}</span><Crest team={home} size="sm"/></span><span className={`md-match-score ${match.score ? 'finished' : ''}`}>{match.score ? `${match.score[0]} – ${match.score[1]}` : match.time}</span><span className="md-match-team"><Crest team={away} size="sm"/><span>{t(away.name, away.ar)}</span></span><span className="md-match-venue">{match.venue}<small>{match.score ? t('Full time','انتهت') : t('Confirmed','مؤكدة')}</small></span><Icon name="chevron" size={16}/></Link>;
}
export function Dashboard() {
  const { t, state, update, notify } = useMaydan(); const attending = state.attendance.m6;
  return <>
    <PageTitle eyebrow={t('TUESDAY, 15 SEPTEMBER 2026', 'الثلاثاء، ١٥ سبتمبر ٢٠٢٦')} title={t('Good to see you, Ahmad.', 'أهلًا أحمد، نوّرت.')} description={t('A new week. Another chance to leave it all on the pitch.', 'أسبوع جديد، وفرصة جديدة تعطي كل اللي عندك بالملعب.')}><Action href="/hub/leagues" secondary icon="trophy">{t('Explore leagues', 'اكتشف الدوريات')}</Action></PageTitle>
    <div className="md-dashboard-top"><section className="md-match-hero"><div className="md-hero-content"><div className="md-hero-meta"><span className="md-live-dot"/>{t('UP NEXT · MATCHWEEK 6', 'القادم · الجولة السادسة')}<span className="md-hero-league">{t('JENIN AUTUMN LEAGUE', 'دوري جنين الخريفي')}</span></div><h2>{t('Friday nights.', 'ليالي الجمعة.')}<br/><span>{t('Our kind of football.', 'هاي كرتنا.')}</span></h2><div className="md-hero-fixture"><div><Crest team="jenin" size="lg"/><b>{t('Jenin United', 'جنين يونايتد')}</b></div><span className="md-versus">VS</span><div><Crest team="shabab" size="lg"/><b>{t('Shabab Jenin', 'شباب جنين')}</b></div></div><div className="md-hero-details"><span><Icon name="calendar" size={16}/>{t('Fri, 18 Sep · 20:00', 'الجمعة، ١٨ سبتمبر · ٢٠:٠٠')}</span><span><Icon name="pin" size={16}/>{t('Al Baladi Stadium', 'ملعب البلدية')}</span></div><div className="md-hero-bottom"><Link href="/hub/matches/m6" className="md-hero-button">{t('Match details', 'تفاصيل المباراة')}<Icon name="arrow" size={17}/></Link><span><Icon name="shield" size={14}/>{t('Venue & referee confirmed', 'الملعب والحكم مؤكّدين')}</span></div></div><span className="md-hero-edition">LOCAL GAME. BIG FEELING.</span></section>
    <section className="md-card md-readiness"><div className="md-card-heading"><h2>{t('Ready for Friday?', 'جاهز للجمعة؟')}</h2><Icon name="ball" size={19}/></div><p>{t('Your team is counting on you.', 'فريقك معتمد عليك.')}</p><div className="md-attendance"><span className="md-attendance-number">{attending === false ? 6 : 7}<small>/ 9</small></span><span>{t('players confirmed', 'لاعبين أكدوا حضورهم')}<small>{t('Looking good for kickoff', 'جاهزين لضربة البداية')}</small></span></div><div className="md-avatar-stack">{['AD','OK','YN','MS','KH'].map((p,i) => <span key={p} style={{ background: ['#e5e9df','#e6dfd3','#dfe7e9','#e3dbd3','#dce3cd'][i] }}>{p}</span>)}<span>+2</span></div><div className="md-availability-prompt"><span>{t('Can you make it?', 'رح تكون معنا؟')}</span><div><button className={attending !== false ? 'selected' : ''} onClick={() => { update(s => ({ ...s, attendance: { ...s.attendance, m6: true } })); notify(t('You’re in. Attendance saved.', 'أكدنا حضورك.')); }}><Icon name="check" size={15}/>{t('I’m in', 'أنا معكم')}</button><button className={attending === false ? 'selected no' : ''} onClick={() => { update(s => ({ ...s, attendance: { ...s.attendance, m6: false } })); notify(t('Your availability has been updated.', 'تم تحديث حضورك.')); }}>{t('Can’t make it', 'مش قادر')}</button></div></div><Link className="md-readiness-footer" href="/hub/team/lineup">{t('View the matchday squad', 'شوف تشكيلة المباراة')}<Icon name="arrow" size={16}/></Link></section></div>
    <div className="md-stat-strip">{[['trophy',t('League position','المركز بالدوري'),'02',t('of 8 teams','من ٨ فرق'),t('↑ 1 place','↑ مركز واحد')],['ball',t('Matches played','مبارياتك'),'05',t('this season','هذا الموسم'),t('3W · 1D · 1L','٣ فوز · ١ تعادل · ١ خسارة')],['flag',t('Your goals','أهدافك'),'04',t('this season','هذا الموسم'),t('↑ 2 last match','↑ ٢ آخر مباراة')],['chart',t('Your assists','تمريراتك الحاسمة'),'06',t('this season','هذا الموسم'),t('#1 in your team','الأول في فريقك')]].map(([icon,label,value,sub,note]) => <Link href={icon === 'trophy' ? '/hub/leagues/jenin-autumn' : '/hub/profile'} className="md-stat" key={label}><span className="md-stat-label"><Icon name={icon} size={17}/>{label}</span><div><b>{value}</b><span>{sub}</span></div><small>{note}</small></Link>)}</div>
    <div className="md-dashboard-middle"><section className="md-card"><SectionTitle title={t('The league picture', 'صورة الدوري')} subtitle={t('Jenin Autumn League · Matchweek 5 of 7', 'دوري جنين الخريفي · الجولة ٥ من ٧')} href="/hub/leagues/jenin-autumn" action={t('Full table', 'الجدول كامل')}/><Standings compact/><div className="md-table-note"><span className="md-small-dot"/>{t('Three points off the top. Keep pushing.', 'ثلاث نقاط عن الصدارة. كمّلوا.')}</div></section><section className="md-card"><SectionTitle title={t('Around the club', 'أخبار النادي')} href="/hub/matches" action={t('Match centre', 'المباريات')}/><Link href="/hub/matches/m5" className="md-news-item"><span className="md-news-icon"><Icon name="trophy"/></span><div><small>{t('RESULT CONFIRMED', 'نتيجة مؤكدة')}</small><h3>{t('Three goals. Three points.', 'ثلاث أهداف. ثلاث نقاط.')}</h3><p>{t('A 3–1 win over Al Ittihad moves us up to second.', 'فوز ٣–١ على الاتحاد يرفعنا للمركز الثاني.')}</p><span>{t('Yesterday', 'أمس')}</span></div></Link><Link href="/hub/payments" className="md-news-item"><span className="md-news-icon amber"><Icon name="wallet"/></span><div><small>{t('TEAM PAYMENT', 'دفعة الفريق')}</small><h3>{t('A little admin before kickoff.', 'شوية ترتيب قبل المباراة.')}</h3><p>{t('Matchweek 6 installment of ₪125 is due Friday.', 'دفعة الجولة السادسة ١٢٥ شيكل مستحقة الجمعة.')}</p><span>{t('View payment details', 'تفاصيل الدفعة')} ↗</span></div></Link></section></div>
    <div className="md-dashboard-bottom"><section className="md-card"><SectionTitle title={t('On the calendar', 'على الروزنامة')} href="/hub/matches" action={t('All fixtures', 'كل المباريات')}/>{matches.slice(0,2).map(m => <MatchRow key={m.id} match={m}/>)}</section><Link href="/hub/discover" className="md-recruit-banner"><span className="md-eyebrow">{t('BETTER TOGETHER', 'مع بعض أقوى')}</span><h3>{t('Your next teammate', 'زميلك الجاي')}<br/>{t('is out there.', 'ناطر بالملعب.')}</h3><span>{t('Find local players', 'اكتشف لاعبين قريبين')}<Icon name="arrow" size={17}/></span><Icon name="users" size={80}/></Link></div>
  </>;
}

export function PlayerLeaders() { const { t } = useMaydan(); return <div className="md-leader-list">{[...players].sort((a,b) => b.goals-a.goals).slice(0,5).map((p,i) => <Link href={`/hub/players/${p.id}`} key={p.id}><span className="md-rank">{i+1}</span><span className="md-avatar">{p.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><span><b>{t(p.name,p.ar)}</b><small>{t(p.position)}</small></span><strong>{p.goals}<small>{t('goals','أهداف')}</small></strong></Link>)}</div>; }

